server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
   console:
    enabled: true
    path: /h2-console

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}

mail:
  host: ${MAIL_HOST:localhost}
  port: ${MAIL_PORT:1025}
  username: ${MAIL_USERNAME:test}
  password: ${MAIL_PASSWORD:test}

jwt:
  secret: ${JWT_SECRET:mysecretkey}
  expiration: ${JWT_EXPIRATION:86400000}